### ISSUE TITLE
How to wrap the text in the list

### ISSUE THREAD

**Issue by kathirsuresh** [ffrm/react-native-modal-select-list#5]
In the list i want to display full address with city and state. But i can't wrap the label value.

**Comment by asnando** [comment]
Hi @kathirsuresh,

Did you managed to solve this? I've added the new `numberOfLines` property which enables the row text to display the maximun of n lines instead of the fixed 1. 

Commit: f19e6b3

I believe you are trying to display the address as multiline text and hope this property helps you. Otherwise, let me know.

<img src="https://user-images.githubusercontent.com/33915907/73488460-be441400-4387-11ea-8af6-7bbd1f637b03.png" height="1024" />
